### ISSUE TITLE
Swift5 compatibility

### ISSUE THREAD

**Issue by varadig** [tuarua/Firebase-ANE#31]
QUESTION:

There is plane rethink/write for swift5?
There is stable ABI, which is good for reduce application size.
Now I need to include all the dynamiclib to my app what size is very big (105Mb) and just the frameworks size is 81.1Mb
https://www.dropbox.com/s/6xxmpgsfpfpmsmn/Screenshot%202019-04-03%2010.00.45.png?dl=0
**Another question.**
I use just the FCM and the RemoteConfig. Which dynamiclib necessary to include?

Thanks.

Sorry for delete the template, but it is not a bug, just a question.

**Comment by tuarua** [comment]
Not yet - Firebase frameworks are all static libraries and there are problems with building Swift static libraries under 5.0 - possibly because AIR is still built against 12.1

Even with ABI stability unless you set your App's minimum target as 12.2 you still have to package the dylibs to support lesser versions of iOS.

You can exclude AVFoundation, simd, Accelerate if not using Vision/MLKit. All others are needed.

-----

Don't confuse IPA size with the size of the final app in the App Store.
 
The size increase are the official Apple Swift libraries. If you build an iOS app with Swift in Xcode it produces an ipa with the same Swift files (which is most new apps now)
 
It's important to know that this doesn't mean a user who downloads the app from the app store downloads a file the same size as your ipa.
After you upload the ipa Apple compress/strip/thin the app
 
Apple say this 

> The size of libswiftCore.dylib in your IPA, and the size of your IPA in general, is somewhat meaningless these days. The new thinning features in the store will remove unnecessary content from your app when delivering to specific devices, and libswiftCore.dylib contains bitcode even if your app doesn't. This bitcode is removed before your app is downloaded to a customer device.

 https://stackoverflow.com/questions/41907323/what-is-the-file-size-overhead-of-the-bundled-swift-libraries-compared-to-an-obj

**Comment by varadig** [comment]
Thanks for the satisfactory answers!
