### ISSUE TITLE
Crashlytics example project stay on Build and run your app

### ISSUE THREAD

**Issue by varadig** [tuarua/Firebase-ANE#37]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
Run example app of FirebaseANE, with refistered Firebase project and apply google-service.json to the value.xml file and rebuild FirebaseANE
    
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1
latest: 0.6.0

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?
Samsung Galaxy J5
- **With which operating system?**
    - iOS 11, Android 7 etc?
Android 6.0.1

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?
macOs Mojave

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
IntelliJ

- **Which version of AIR are you using?**
    - 29, 30.. etc?
33

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
I follow the setup of the Crashlytics wiki, configure the Crashlytics on Firebase console, and...

> Build and run your app
> We'll be listening for your app to communicate with our servers.
> 

- **What is the expected output? What do you see instead?**
Cant get any crash/log/exception log

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.
[trace] apiKey XXXXXXXXXXX
[trace] googleAppId XXXXXXXXXXX

[trace] storageBucket testfirebaseane.appspot.com
[trace] [Starling] Context restored.

- **Does this problem also occur in the Sample Application provided?**
Yes, exactly

**Comment by tuarua** [comment]
How long did you wait for the log to appear in the Firebase console ?

**Comment by varadig** [comment]
~20h.
But if I check now, the console said me:

https://www.dropbox.com/s/n0466kusa9l4zk8/Screenshot%202019-10-11%2014.12.15.png?dl=0

**Comment by tuarua** [comment]
Everything is working for me.

Try these steps

1. Build a release version
2. Click the force crash button in the AIR app.
3. Re-open the app
4. Wait a few hours

From memory, crashlytics are **pooled** sent when the app is **opened again**

![image](https://user-images.githubusercontent.com/12083217/66685228-c3b00e00-ec73-11e9-8f94-be0595dc5fe0.png)

**Comment by varadig** [comment]
Here every time I open the Crashlytics menu I got the setup process suggestion:


[Untitled.mov.zip](https://github.com/tuarua/Firebase-ANE/files/3720216/Untitled.mov.zip)

**Comment by tuarua** [comment]
Well pointing at the problem again is not going to solve it.

From my perspective the ANE code is working correctly. It simply wraps the native code.
eg:

https://github.com/tuarua/Firebase-ANE/blob/a5a4efd9ff03a6145fa82f776f3ae80bbed24b4e/native_library/android/FirebaseANE/Crashlytics/src/main/java/com/tuarua/firebase/crashlytics/CrashlyticsActivity.kt#L27

So the problem is elsewhere.
As I'm sure you understand I don't work for Google support so the onus is not on me to spend time investigating on stack overflow or opening a ticket with Firebase support team. That is up to you to do.  You should at least run logcat to check what the device logs are to see any logs related to Crashlytics.
